### ISSUE TITLE
Lidarr support ?

### ISSUE THREAD

**Issue by JamesDAdams** [RandomNinjaAtk/docker-atd#1]
Hi, 

i see this in the readme :  `-e LidarrUrl=http://x.x.x.x:8686 | ONLY used if Lidarr List Import is enabled...`

So your app supports the request for movies via lidarr ?

**Comment by RandomNinjaAtk** [comment]
This is a work in-progress and not ready...yet. So not all details are technically correct. Suggest using discord to discuss further
